### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by darrenwiens** [developmentseed/sentinel-2-cog#1]
`docker-compose build --no-cache` fails to build due to numpy=0.1.17 issues (more info [here](https://github.com/numpy/numpy/issues/14147)).

Fix seems to be, in [Dockerfile](https://github.com/developmentseed/sentinel-2-cog/blob/master/Dockerfile#L11): `RUN CFLAGS='-std=c99' pip3 install . --no-binary numpy -t $PACKAGE_PREFIX -U`

Alternative solution is to force an earlier numpy version (e.g. 0.1.16).

Happy to make a PR if either option looks good to you.

**Comment by vincentsarago** [comment]
sorry @phloem7 I've seen the notification.

we need to add `CFLAGS="--std=c99"` in the env to overpass this. 

ref: https://github.com/numpy/numpy/issues/14147

**Comment by vincentsarago** [comment]
thanks for the issue @phloem7 I'll fix this

**Comment by vincentsarago** [comment]
closed by d24ec71284ab
